"""
Login de YouTube via Google OAuth usando un browser real (Selenium).

Flujo:
  1. Abre una ventana de Chrome visible (undetected-chromedriver)
  2. Navega a la página de login de Google para YouTube
  3. El usuario completa el login de Google normalmente (OAuth real)
  4. Detecta automáticamente cuando el login está completo
  5. Exporta las cookies en formato Netscape para yt-dlp
  6. Cierra el browser

El proceso corre en un hilo de background para no bloquear la API.
"""
from __future__ import annotations

import logging
import threading
import time
from pathlib import Path
from typing import Any

log = logging.getLogger("auth.browser_login")


def _get_chrome_major_version() -> int | None:
    """Detecta la versión mayor de Chrome instalada en el sistema."""
    import subprocess, re
    try:
        # Windows: buscar en registro o ejecutar Chrome con --version
        for cmd in [
            ["reg", "query", r"HKEY_CURRENT_USER\Software\Google\Chrome\BLBeacon", "/v", "version"],
            ["reg", "query", r"HKEY_LOCAL_MACHINE\SOFTWARE\Google\Chrome\BLBeacon", "/v", "version"],
        ]:
            result = subprocess.run(cmd, capture_output=True, text=True, timeout=5)
            if result.returncode == 0:
                match = re.search(r"(\d+)\.\d+\.\d+\.\d+", result.stdout)
                if match:
                    return int(match.group(1))
    except Exception:
        pass
    return None

ROOT = Path(__file__).resolve().parent.parent.parent
_COOKIES_PATH = ROOT / "data" / "yt_cookies.txt"

# Estado compartido del proceso de login
_state: dict[str, Any] = {
    "status": "idle",          # idle | waiting_login | capturing | done | error
    "started_at": None,
    "finished_at": None,
    "error": None,
    "cookies_count": 0,
}
_state_lock = threading.Lock()
_login_thread: threading.Thread | None = None


def _set_state(**kwargs: Any) -> None:
    with _state_lock:
        _state.update(kwargs)


def get_login_state() -> dict[str, Any]:
    with _state_lock:
        return dict(_state)


# ─── Conversión de cookies Selenium → Netscape ────────────────────────────────

def _to_netscape(cookies: list[dict[str, Any]]) -> str:
    """Convierte la lista de cookies de Selenium al formato Netscape que usa yt-dlp."""
    lines = ["# Netscape HTTP Cookie File", "# Generated by SYJ WebScrapper auth module", ""]

    for c in cookies:
        domain = c.get("domain", "")
        if not domain:
            continue
        # Netscape format: domain  include_subdomains  path  secure  expiry  name  value
        include_subdomains = "TRUE" if domain.startswith(".") else "FALSE"
        secure = "TRUE" if c.get("secure", False) else "FALSE"
        expiry = int(c.get("expiry", 0) or 0)
        path = c.get("path", "/")
        name = c.get("name", "")
        value = c.get("value", "")

        lines.append(f"{domain}\t{include_subdomains}\t{path}\t{secure}\t{expiry}\t{name}\t{value}")

    return "\n".join(lines) + "\n"


# ─── Auth cookie names that indicate a logged-in YouTube session ──────────────

_AUTH_COOKIE_NAMES = {
    "__Secure-3PSID",
    "__Secure-1PSID",
    "SAPISID",
    "SID",
    "HSID",
    "APISID",
}


def _is_logged_in(cookies: list[dict[str, Any]]) -> bool:
    names = {c["name"] for c in cookies}
    return bool(names & _AUTH_COOKIE_NAMES)


# ─── Login worker ─────────────────────────────────────────────────────────────

def _run_browser_login(timeout_seconds: int = 300) -> None:
    """Hilo de background: abre Chrome, espera login, exporta cookies."""
    try:
        from selenium import webdriver
        from selenium.webdriver.chrome.options import Options
        from selenium.webdriver.chrome.service import Service
        from webdriver_manager.chrome import ChromeDriverManager

        _set_state(status="waiting_login", started_at=time.time(), error=None)
        log.info("Abriendo Chrome para login de Google/YouTube...")

        options = Options()
        options.add_argument("--start-maximized")
        options.add_argument("--disable-blink-features=AutomationControlled")
        options.add_experimental_option("excludeSwitches", ["enable-automation"])
        options.add_experimental_option("useAutomationExtension", False)
        # NO headless — el usuario debe interactuar

        service = Service(ChromeDriverManager().install())
        driver = webdriver.Chrome(service=service, options=options)

        try:
            # Navegar al login de Google optimizado para YouTube
            driver.get("https://accounts.google.com/ServiceLogin?service=youtube&continue=https://www.youtube.com")
            log.info("Browser abierto. Esperando que el usuario complete el login...")

            deadline = time.time() + timeout_seconds
            logged_in = False

            while time.time() < deadline:
                try:
                    current_url = driver.current_url
                    cookies = driver.get_cookies()

                    if _is_logged_in(cookies):
                        # Navegar a YouTube para capturar todas las cookies del dominio
                        if "youtube.com" not in current_url:
                            driver.get("https://www.youtube.com")
                            time.sleep(3)
                            cookies = driver.get_cookies()

                        if _is_logged_in(cookies):
                            logged_in = True
                            break
                except Exception:
                    pass

                time.sleep(2)

            if not logged_in:
                _set_state(status="error", error="Timeout: el usuario no completó el login.")
                return

            # ── Capturar y guardar cookies ──────────────────────────────
            _set_state(status="capturing")
            log.info("Login detectado. Capturando cookies...")

            # Navegar por páginas de YouTube para obtener todas las cookies
            driver.get("https://www.youtube.com")
            time.sleep(2)

            all_cookies = driver.get_cookies()
            yt_cookies = [c for c in all_cookies if "youtube.com" in c.get("domain", "") or "google.com" in c.get("domain", "")]

            netscape_content = _to_netscape(yt_cookies)
            _COOKIES_PATH.parent.mkdir(parents=True, exist_ok=True)
            _COOKIES_PATH.write_text(netscape_content, encoding="utf-8")

            auth_found = [c["name"] for c in yt_cookies if c["name"] in _AUTH_COOKIE_NAMES]
            log.info("Cookies exportadas: %d total, auth cookies: %s", len(yt_cookies), auth_found)

            _set_state(
                status="done",
                finished_at=time.time(),
                cookies_count=len(yt_cookies),
            )

        finally:
            try:
                driver.quit()
            except Exception:
                pass

    except ImportError:
        _set_state(
            status="error",
            error="undetected-chromedriver no disponible. Asegúrate de que está instalado.",
        )
    except Exception as exc:
        log.error("Error en browser login: %s", exc)
        _set_state(status="error", error=str(exc))


# ─── API pública ──────────────────────────────────────────────────────────────

def start_login(timeout_seconds: int = 300) -> dict[str, Any]:
    """
    Inicia el proceso de login en background.
    Retorna inmediatamente con el estado inicial.
    """
    global _login_thread

    with _state_lock:
        current = _state["status"]

    if current == "waiting_login":
        return {"already_running": True, **get_login_state()}

    _login_thread = threading.Thread(
        target=_run_browser_login,
        kwargs={"timeout_seconds": timeout_seconds},
        daemon=True,
        name="youtube-browser-login",
    )
    _login_thread.start()
    time.sleep(0.5)  # dar tiempo al hilo para inicializar

    return {
        "already_running": False,
        "message": (
            "Se abrirá una ventana de Chrome. "
            "Inicia sesión en tu cuenta de Google y luego ve a youtube.com. "
            "Las cookies se capturarán automáticamente."
        ),
        **get_login_state(),
    }
